import 'package:flutter/material.dart';
import 'package:audioplayers/audioplayers.dart';
import 'package:flutter/services.dart';
import 'dart:math';

void main() {
  runApp(FigmaToCodeApp());
}

// Generated by: https://www.figma.com/community/plugin/842128343887142055/
class FigmaToCodeApp extends StatelessWidget {
  static final AudioPlayer audioPlayer = AudioPlayer();
  //aaa
  bool isPlaying = false;
  String currentMusicPath = "";

  //HAPPY
  List<String> musicFiles1 = [
    "assets/happy_2.mp3",
    "assets/happy-2.mp3",
  ];

//SAD
  List<String> musicFiles2 = [
    "assets/New_Composition_6.mp3",
    "assets/SAD2.mp3",
    "assets/SAD3.mp3"
  ];

//ANGRY
  List<String> musicFiles3 = [
    "assets/ANGRY1.mp3",
    "assets/ANGRY2.mp3",
    "assets/ANGRY3.mp3"
  ];

//EMOTION
  List<String> musicFiles4 = [
    "assets/EMOTION1.mp3",
    "assets/EMOTION2.mp3",
    "assets/EMOTIOM3.mp3"
  ];

//PEACE
  List<String> musicFiles5 = [
    "assets/peace.mp3",
    "assets/peace-2.mp3",
  ];

  void playRandomMusic(List<String> musicFiles1) async {
    Random random = Random();
    int randomIndex = random.nextInt(musicFiles1.length);
    currentMusicPath = musicFiles1[randomIndex];
    audioPlayer.play(DeviceFileSource(currentMusicPath));
    isPlaying = true;
  }

  void stopMusic() async {
    await audioPlayer.stop();
    isPlaying = false;
  }

  void toggleMusic(List<String> musicFiles1) {
    print(isPlaying);
    if (isPlaying == true) {
      stopMusic();
    } else if (isPlaying == false) {
      playRandomMusic(musicFiles1);
    }
  }

  void playRandomMusic2(List<String> musicFiles2) async {
    Random random = Random();
    int randomIndex = random.nextInt(musicFiles2.length);
    currentMusicPath = musicFiles2[randomIndex];
    audioPlayer.play(DeviceFileSource(currentMusicPath));
    isPlaying = true;
  }

  void stopMusic2() async {
    await audioPlayer.stop();
    isPlaying = false;
  }

  void toggleMusic2(List<String> musicFiles2) {
    print(isPlaying);
    if (isPlaying == true) {
      stopMusic();
    } else if (isPlaying == false) {
      playRandomMusic(musicFiles2);
    }
  }

  void playRandomMusic3(List<String> musicFiles3) async {
    Random random = Random();
    int randomIndex = random.nextInt(musicFiles3.length);
    currentMusicPath = musicFiles3[randomIndex];
    audioPlayer.play(DeviceFileSource(currentMusicPath));
    isPlaying = true;
  }

  void stopMusic3() async {
    await audioPlayer.stop();
    isPlaying = false;
  }

  void toggleMusic3(List<String> musicFiles3) {
    print(isPlaying);
    if (isPlaying == true) {
      stopMusic();
    } else if (isPlaying == false) {
      playRandomMusic(musicFiles3);
    }
  }

  void playRandomMusic4(List<String> musicFiles4) async {
    Random random = Random();
    int randomIndex = random.nextInt(musicFiles4.length);
    currentMusicPath = musicFiles4[randomIndex];
    audioPlayer.play(DeviceFileSource(currentMusicPath));
    isPlaying = true;
  }

  void stopMusic4() async {
    await audioPlayer.stop();
    isPlaying = false;
  }

  void toggleMusic4(List<String> musicFiles4) {
    print(isPlaying);
    if (isPlaying == true) {
      stopMusic();
    } else if (isPlaying == false) {
      playRandomMusic(musicFiles4);
    }
  }

  void playRandomMusic5(List<String> musicFiles5) async {
    Random random = Random();
    int randomIndex = random.nextInt(musicFiles5.length);
    currentMusicPath = musicFiles5[randomIndex];
    audioPlayer.play(DeviceFileSource(currentMusicPath));
    isPlaying = true;
  }

  void stopMusic5() async {
    await audioPlayer.stop();
    isPlaying = false;
  }

  void toggleMusic5(List<String> musicFiles5) {
    print(isPlaying);
    if (isPlaying == true) {
      stopMusic();
    } else if (isPlaying == false) {
      playRandomMusic(musicFiles5);
    }
  }

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: [
          Homescreen(),
        ]),
      ),
    );
  }
}

class Homescreen extends StatelessWidget {
  final player01 = AudioPlayer();

  @override
  Widget build(BuildContext context) {
    return Column(
      children: [
        Container(
          width: 390,
          height: 844,
          clipBehavior: Clip.antiAlias,
          decoration: BoxDecoration(color: Colors.black),
          child: Stack(
            children: [
              Positioned(
                left: 219.01,
                top: 65,
                child: Transform(
                  transform: Matrix4.identity()
                    ..translate(0.0, 0.0)
                    ..rotateZ(0.15),
                  child: Transform.scale(
                    scale: 1.0,
                    child: MaterialButton(
                      textColor: Colors.red,
                      child: Container(
                        width: 175,
                        height: 175,
                        decoration: BoxDecoration(
                            image: DecorationImage(
                          image: NetworkImage('images/Angry.png'),
                          fit: BoxFit.cover,
                        )),
                        child: Padding(padding: const EdgeInsets.all(20.0)),
                      ),
                      onPressed: () {
                        Navigator.push(
                          context,
                          MaterialPageRoute(
                              builder: (context) => ThirdScreen()),
                        );
                      },
                      shape: OvalBorder(),
                    ),
                  ),
                ),
              ),
              //怒りのボタンここまで
              Positioned(
                left: 20,
                top: 694,
                child: Container(
                  width: 370,
                  height: 110,
                  decoration: ShapeDecoration(
                    color: Color.fromARGB(255, 182, 41, 161),
                    shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(47),
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 37,
                top: 707,
                child: SizedBox(
                  width: 353,
                  height: 75,
                  child: Text(
                    'どんな気分？',
                    textAlign: TextAlign.center,
                    style: TextStyle(
                      color: Colors.white,
                      fontSize: 45,
                      fontFamily: 'Inter',
                      fontWeight: FontWeight.w600,
                      height: 0,
                      letterSpacing: 3.15,
                    ),
                  ),
                ),
              ),
              Positioned(
                left: 124,
                top: 770,
                child: Text(
                  '顔をタップして！',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Colors.white,
                    fontSize: 20,
                    fontFamily: 'Inter',
                    fontWeight: FontWeight.w600,
                    height: 0,
                    letterSpacing: 1.40,
                  ),
                ),
              ),
              //ここまでは押せないボタンのところ

              Positioned(
                left: 40.13,
                top: 147,
                child: Transform(
                  transform: Matrix4.identity()
                    ..translate(0.0, 0.0)
                    ..rotateZ(0.15),
                  child: Transform.scale(
                    scale: 1.0,
                    child: Container(
                      width: 174.16,
                      height: 174.66,
                      child: MaterialButton(
                        textColor: Colors.green,
                        child: Container(
                          decoration: BoxDecoration(
                              image: DecorationImage(
                            image: NetworkImage('images/Peace.png'),
                            fit: BoxFit.cover,
                          )),
                          child: Padding(
                            padding: const EdgeInsets.all(100.0),
                          ),
                        ),
                        onPressed: () {
                          Navigator.push(
                              context,
                              MaterialPageRoute(
                                builder: (context) => FifthScreen(),
                              ));
                        },
                        shape: OvalBorder(),
                      ),
                    ),
                  ),
                ),
              ),
              //Peaceのボタンここまで

              Positioned(
                left: 230.01,
                top: 270,
                child: Transform(
                  transform: Matrix4.identity()
                    ..translate(0.0, 0.0)
                    ..rotateZ(0.15),
                  child: Transform.scale(
                    scale: 1.0,
                    child: Container(
                        width: 175,
                        height: 175,
                        child: MaterialButton(
                          textColor: Colors.purple,
                          child: Container(
                            decoration: BoxDecoration(
                                image: DecorationImage(
                              image: NetworkImage('images/Emotion.png'),
                              fit: BoxFit.cover,
                            )),
                            child: Padding(
                              padding: const EdgeInsets.all(100.0),
                            ),
                          ),
                          onPressed: () {
                            Navigator.push(
                                context,
                                MaterialPageRoute(
                                  builder: (context) => FourthScreen(),
                                ));
                          },
                          shape: OvalBorder(),
                        )),
                  ),
                ),
              ),
              //えもボタンここまで

              Positioned(
                left: 20.13,
                top: 380,
                child: Transform(
                  transform: Matrix4.identity()
                    ..translate(0.0, 0.0)
                    ..rotateZ(0.15),
                  child: Transform.scale(
                    scale: 1.0,
                    child: Container(
                      width: 175.20,
                      height: 175.87,
                      child: MaterialButton(
                        textColor: Colors.blue,
                        child: Container(
                          decoration: BoxDecoration(
                              image: DecorationImage(
                            image: NetworkImage('images/Sad.png'),
                            fit: BoxFit.cover,
                          )),
                          child: Padding(padding: const EdgeInsets.all(100.0)),
                        ),
                        onPressed: () {
                          Navigator.push(
                            context,
                            MaterialPageRoute(
                                builder: (context) => SecondScreen()),
                          );
                        },
                        shape: OvalBorder(),
                      ),
                    ),
                  ),
                ),
              ),
              //悲しいボタンここまで

              Positioned(
                left: 209.01,
                top: 487,
                child: Transform(
                  transform: Matrix4.identity()
                    ..translate(0.0, 0.0)
                    ..rotateZ(0.15),
                  child: Transform.scale(
                    scale: 1.2,
                    child: Container(
                      width: 168.20,
                      height: 165.87,
                      child: MaterialButton(
                        textColor: Colors.yellow,
                        child: Container(
                          decoration: BoxDecoration(
                              image: DecorationImage(
                            image: NetworkImage('images/Happy.png'),
                            fit: BoxFit.cover,
                          )),
                        ),
                        onPressed: () {
                          Navigator.push(
                              context,
                              MaterialPageRoute(
                                  builder: (context) => FirstScreen()));
                        },
                        shape: OvalBorder(),
                      ),
                    ),
                  ),
                ),
              ),
              //はっぴーここまで
            ],
          ),
        ),
      ],
    );
  }
}

class FirstScreen extends StatelessWidget {
  FirstScreen({super.key});

  final audioPlayer = AudioPlayer();

  bool isPlaying = false;

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
          toolbarHeight: 30.0, // 適切な高さを設定
          title: Text('再生したら止められない!!',
              style: TextStyle(color: Color.fromARGB(255, 255, 255, 255))),
          backgroundColor: Color.fromARGB(255, 0, 0, 0)),
      body: Center(
        child: Stack(
          children: [
            Container(
              width: double.infinity,
              height: double.infinity,
              decoration: BoxDecoration(
                image: DecorationImage(
                  image: NetworkImage('images/image_6483441 (9).JPG'),
                  fit: BoxFit.cover,
                ),
              ),
            ),
            // ボタンを表示するコンテナ（画像の上に重ねる）
            Positioned(
              bottom: 75, // 画像の下端からの距離を調整
              left: 0,
              right: 20,
              child: Column(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: [
                  ElevatedButton(
                    onPressed: () {
                      FigmaToCodeApp()
                          .toggleMusic(FigmaToCodeApp().musicFiles1);
                    },
                    style: ElevatedButton.styleFrom(
                      primary: Color.fromARGB(255, 0, 0, 0), // ボタンの背景色を緑色に設定
                      onPrimary:
                          Color.fromARGB(255, 252, 252, 252), // ボタンのテキスト色を白色に設定
                    ),
                    child: Container(
                      width: 200, // 幅を指定
                      height: 200, // 高さを指定
                      child: Center(
                        child: Text(
                          FigmaToCodeApp().isPlaying ? '❙❙' : '▶',
                          style: TextStyle(fontSize: 100),
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class SecondScreen extends StatelessWidget {
  final audioPlayer = AudioPlayer();

  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
          toolbarHeight: 30.0, // 適切な高さを設定
          title: Text('再生したら止められない!!',
              style:
                  TextStyle(color: const Color.fromARGB(255, 255, 255, 255))),
          backgroundColor: Color.fromARGB(255, 0, 0, 0)),
      body: Center(
        child: Stack(
          children: [
            Container(
              width: double.infinity,
              height: double.infinity,
              decoration: BoxDecoration(
                image: DecorationImage(
                  image: NetworkImage('images/image_6483441 (11).JPG'),
                  fit: BoxFit.cover,
                ),
              ),
            ),
            // ボタンを表示するコンテナ（画像の上に重ねる）
            Positioned(
              bottom: 75, // 画像の下端からの距離を調整
              left: 0,
              right: 20,
              child: Column(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: [
                  ElevatedButton(
                    onPressed: () {
                      FigmaToCodeApp()
                          .toggleMusic2(FigmaToCodeApp().musicFiles2);
                    },
                    style: ElevatedButton.styleFrom(
                      primary: Color.fromARGB(255, 0, 0, 0), // ボタンの背景色を緑色に設定
                      onPrimary: Colors.white, // ボタンのテキスト色を白色に設定
                    ),
                    child: Container(
                      width: 200, // 幅を指定
                      height: 200, // 高さを指定
                      child: Center(
                        child: Text(
                          '▶',
                          style: TextStyle(fontSize: 100),
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class ThirdScreen extends StatelessWidget {
  final audioPlayer = AudioPlayer();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
          toolbarHeight: 30.0, // 適切な高さを設定
          title: Text('再生したら止められない!!',
              style:
                  TextStyle(color: const Color.fromARGB(255, 255, 255, 255))),
          backgroundColor: Color.fromARGB(255, 0, 0, 0)),
      body: Center(
        child: Stack(
          children: [
            Container(
              width: double.infinity,
              height: double.infinity,
              decoration: BoxDecoration(
                image: DecorationImage(
                  image: NetworkImage('images/image_6483441 (12).JPG'),
                  fit: BoxFit.cover,
                ),
              ),
            ),
            // ボタンを表示するコンテナ（画像の上に重ねる）
            Positioned(
              bottom: 75, // 画像の下端からの距離を調整
              left: 0,
              right: 20,
              child: Column(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: [
                  ElevatedButton(
                    onPressed: () {
                      // 音楽を再生
                      FigmaToCodeApp()
                          .toggleMusic3(FigmaToCodeApp().musicFiles3);
                    },
                    style: ElevatedButton.styleFrom(
                      primary: Color.fromARGB(255, 0, 0, 0), // ボタンの背景色を緑色に設定
                      onPrimary:
                          Color.fromARGB(255, 255, 255, 255), // ボタンのテキスト色を白色に設定
                    ),
                    child: Container(
                      width: 200, // 幅を指定
                      height: 200, // 高さを指定
                      child: Center(
                        child: Text(
                          '▶',
                          style: TextStyle(fontSize: 100),
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class FourthScreen extends StatelessWidget {
  final audioPlayer = AudioPlayer();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
          toolbarHeight: 30.0, // 適切な高さを設定
          title: Text('再生したら止められない！',
              style:
                  TextStyle(color: const Color.fromARGB(255, 255, 255, 255))),
          backgroundColor: Color.fromARGB(255, 0, 0, 0)),
      body: Center(
        child: Stack(
          children: [
            Container(
              width: double.infinity,
              height: double.infinity,
              decoration: BoxDecoration(
                image: DecorationImage(
                  image: NetworkImage('images/image_6483441 (10).JPG'),
                  fit: BoxFit.cover,
                ),
              ),
            ),
            // ボタンを表示するコンテナ（画像の上に重ねる）
            Positioned(
              bottom: 75, // 画像の下端からの距離を調整
              left: 0,
              right: 20,
              child: Column(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: [
                  ElevatedButton(
                    onPressed: () {
                      // 音楽を再生
                      FigmaToCodeApp()
                          .toggleMusic4(FigmaToCodeApp().musicFiles4);
                    },
                    style: ElevatedButton.styleFrom(
                      primary: Color.fromARGB(255, 0, 0, 0), // ボタンの背景色を緑色に設定
                      onPrimary:
                          Color.fromARGB(255, 255, 255, 255), // ボタンのテキスト色を白色に設定
                    ),
                    child: Container(
                      width: 200, // 幅を指定
                      height: 200, // 高さを指定
                      child: Center(
                        child: Text(
                          '▶',
                          style: TextStyle(fontSize: 100),
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}

class FifthScreen extends StatelessWidget {
  final audioPlayer = AudioPlayer();
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
          toolbarHeight: 30.0, // 適切な高さを設定
          title: Text('再生したら止められない！',
              style: TextStyle(color: Color.fromARGB(255, 255, 255, 255))),
          backgroundColor: Color.fromARGB(255, 0, 0, 0)),
      body: Center(
        child: Stack(
          children: [
            Container(
              width: double.infinity,
              height: double.infinity,
              decoration: BoxDecoration(
                image: DecorationImage(
                  image: NetworkImage('images/image_6483441 (13).JPG'),
                  fit: BoxFit.cover,
                ),
              ),
            ),
            // ボタンを表示するコンテナ（画像の上に重ねる）
            Positioned(
              bottom: 75, // 画像の下端からの距離を調整
              left: 0,
              right: 20,
              child: Column(
                mainAxisAlignment: MainAxisAlignment.spaceEvenly,
                children: [
                  ElevatedButton(
                    onPressed: () {
                      FigmaToCodeApp()
                          .toggleMusic5(FigmaToCodeApp().musicFiles5);
                    },
                    style: ElevatedButton.styleFrom(
                      primary: Color.fromARGB(255, 0, 0, 0), // ボタンの背景色を緑色に設定
                      onPrimary:
                          Color.fromARGB(255, 255, 255, 255), // ボタンのテキスト色を白色に設定
                    ),
                    child: Container(
                      width: 200, // 幅を指定
                      height: 200, // 高さを指定
                      child: Center(
                        child: Text(
                          '▶',
                          style: TextStyle(fontSize: 100),
                        ),
                      ),
                    ),
                  ),
                ],
              ),
            ),
          ],
        ),
      ),
    );
  }
}
